project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "Premiere/*/*.ipynb"

website:
  title: "NSI"
  navbar:
    background: "#17202a"
    foreground: "white"
    left:
      - text: "Première"
        menu:
          - text: "IHM"
            href: Premiere/IHM/index.ipynb
          - text: "Intro python"
            href: Premiere/IntroPython/index.ipynb
  
  sidebar:
    - title: "IHM"
      contents:
        - Premiere/IHM/index.ipynb
    - title: "Intro python"
      contents:
        - Premiere/IntroPython/index.ipynb
        - Premiere/IntroPython/variables.ipynb
        - Premiere/IntroPython/condition.ipynb
        - Premiere/IntroPython/boucleFor.ipynb
        - Premiere/IntroPython/boucleWhile.ipynb
        - Premiere/IntroPython/fonction.ipynb
        - Premiere/IntroPython/fiche.ipynb
        - Premiere/IntroPython/controleBlanc.ipynb
        

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/pyodide/v0.27.0/full/pyodide.js"></script>
          <script type="module" src="/scripts/pyodide_init.js"></script>